# Generated by Django 4.0 on 2024-05-19 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0002_remove_item_location_location_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='lands', to='lands.Item'),
        ),
        migrations.AlterField(
            model_name='location',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='lands.item'),
        ),
    ]
