# Generated by Django 4.0 on 2024-05-26 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_is_active'),
        ('lands', '0003_land_items_alter_location_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='land',
            old_name='landlord',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='land',
            name='items',
        ),
        migrations.AddField(
            model_name='item',
            name='land',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lands', to='lands.land'),
        ),
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='users.user'),
            preserve_default=False,
        ),
    ]
