# Generated by Django 4.0 on 2024-07-16 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lands', '0005_itemimage_remove_item_image_item_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='land',
        ),
        migrations.AddField(
            model_name='item',
            name='land',
            field=models.ManyToManyField(related_name='itmes', to='lands.Land'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ManyToManyField(related_name='items', to=settings.AUTH_USER_MODEL),
        ),
    ]
