# Generated by Django 4.0 on 2024-08-02 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_discord_id_user_dsid_and_more'),
        ('lands', '0009_remove_item_lands_remove_item_show_location_land_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lands', to='users.user'),
        ),
    ]
