# Generated by Django 4.0 on 2024-08-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0011_alter_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.URLField(),
        ),
    ]
