# Generated by Django 4.0 on 2024-08-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0012_alter_itemimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='no',
            field=models.IntegerField(null=True),
        ),
    ]
