# Generated by Django 4.0 on 2024-08-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0013_item_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='no',
            field=models.IntegerField(unique=True),
        ),
    ]
