# Generated by Django 4.0 on 2024-08-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0014_alter_item_no'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('land', 'item'), name='unique_land_item'),
        ),
    ]
