# Generated by Django 4.0 on 2024-08-31 08:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lands', '0015_location_unique_land_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='like_cnt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='land',
            name='likeuser_set',
            field=models.ManyToManyField(blank=True, related_name='liked_lands', to=settings.AUTH_USER_MODEL),
        ),
    ]
