# Generated by Django 4.0 on 2024-08-31 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0016_land_like_cnt_land_likeuser_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='lands.item'),
        ),
    ]
