# Generated by Django 4.0 on 2024-08-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_dsname_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dsId',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=64, unique=True),
        ),
    ]
